service: ghost-job-api

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-1

functions:
  api:
    handler: main.handler
    events:
      - httpApi: '*'

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    invalidateCache: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - uvicorn

package:
  patterns:
    - '!.venv/**'
    - '!venv/**'
    - '!.env/**'
    - '!.env'
    - '!node_modules/**'
    - '!.pytest_cache/**'
    - '!__pycache__/**'
    - '!.git/**'
    - '!*.egg-info/**'
    - '!build/**'